### ISSUE TITLE
Question: Comparison to similar libraries

### ISSUE THREAD

**Issue by jvitela** [salvoravida/redux-immer#1]
Hi,

How does this library compares to the function createReducer from Redux Starter Kit?

https://redux-starter-kit.js.org/api/createReducer

**Comment by salvoravida** [comment]
Hi,
first of all redux-immer does not import immer lib, so you can use any version of immer.

But the main goal is to have **one time only produce call, not for reducer.** 

as on readme:
- one time only produce
- standard-like reducers
- support react-router routerReducer integration (redux-first-history / react-router-redux / connected-react-router)
