### ISSUE TITLE
This way of using Immer is not recommended by official documentation

### ISSUE THREAD

**Issue by slouffka** [salvoravida/redux-immer#10]
At first I tried to use redux-immer as a replacement for redux-immutable while porting my code from Immutable to Immer. I've encountered some strange errors related to redux-immer and so I had to spent some time on debugging and eventually read official Immer docs more carefully. I found that official documentation specifically recommends against using single `produce` for all your reducers.

Quote from https://immerjs.github.io/immer/docs/example-reducer:

> Note: it might be tempting after using producers for a while, to just place produce in your root reducer and then pass the draft to each reducer and work directly over said draft. Don't do that. It removes the benefit of using Redux as a system where each reducer is testable as a pure function. Immer is best used when applied to small, individual pieces of logic.

So I changed my code to use combineReducers from Redux and 1. Got rid of all errors. 2. Now have more control over reducers and how to write them. I can use mostly Immer-based reducers and still have an option to optimize critical parts by writing vanilla JS reducers at the same time.

I definitely like the approach recommended by official docs and the flexibility it provides. I think the quote from official docs should be placed in project's README.

I think this repo could be used to educate people how to use Immer properly. Because I came here naturally after using Immutable.js.

**Comment by NE-SmallTown** [comment]
@slouffka Hi, could you give more details about this? It's not very clear for me. Thank!

**Comment by salvoravida** [comment]
@slouffka what errors do you get?

can you provide a codesandbox example?

i do not agree with official raccomandation. you can use one time produce.
