### ISSUE TITLE
Typescript typings error

### ISSUE THREAD

**Issue by hugoburguete** [salvoravida/redux-immer#6]
Hi,

I'm currently getting typing errors when compiling a react app and can't figure out how to fix it.

Please see the screenshot below:
![image](https://user-images.githubusercontent.com/17925235/75789958-6459b400-5d62-11ea-90de-7aaac5ff03d0.png)

Navigating to the file, I can see that there are triple slash directives with references to the types but my compiler doesn't seem to be picking them up.

Here's my tsconfig if it helps:

`{
  "compilerOptions": {
    "sourceMap": false,
    "target": "es5",
    "jsx": "react",
    "allowJs": true,
    "esModuleInterop": true,
    "moduleResolution": "node"
  },
  "exclude": [
    "node_modules"
  ]
}
`

Any ideas?

**Comment by salvoravida** [comment]
have you added immer and redux lib to your package json?

**Comment by hugoburguete** [comment]
yes, I added both the packages and the types for them. 

I am no longer using this package so you're welcome to close this issue unless others might have the same problem
