### ISSUE TITLE
Clarification on use-cases

### ISSUE THREAD

**Issue by raphaelbs** [salvoravida/redux-immer#7]
Hi,

I'm migrating from Immutable to Immer.
I came across with this package but I'm not sure if I need it or not.

My project is using `redux-immutable` and I was considering using the redux `combineReducers`.

Can anyone clarify on the features _one time only produce_ and _standard-like reducers_?

Thanks!

**Comment by salvoravida** [comment]
based on immer guideline you will have to define every reducers suc as
```javascript
import produce from 'immer'

const myreducer1 =  (state = {}, action) =>
  produce(state, draft => {
    switch (action.type) {
      case ADD_TIMER: {
        draft[action.payload.id] = action.payload
        break
      }

      case REMOVE_TIMER: {
        delete draft[action.payload.id]
        break
      }

      case INCREMEMT_RUNNING_TIMERS: {
        Object.values(draft).forEach(timer => {
          if (timer.running) {
            timer.totalTime = getTotalTime(true, timer.starts, timer.stops)
          }
        })
        break
      }

      default:
        return draft
    }
  })
```

and so on....

with redux-immer, you can define reducer normalli without draft and produce, thant use combine-reducer  by redux-immer instead of  "redux" 

for more readme
